# Generated by Django 3.2.6 on 2021-08-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=10)),
                ('first_day', models.DecimalField(decimal_places=10, max_digits=20)),
                ('second_day', models.DecimalField(decimal_places=10, max_digits=20)),
                ('third_day', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fourth_day', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fifth_day', models.DecimalField(decimal_places=10, max_digits=20)),
                ('sixth_day', models.DecimalField(decimal_places=10, max_digits=20)),
                ('seventh_day', models.DecimalField(decimal_places=10, max_digits=20)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
